# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: aSPlzcYUamQSWcAAJuzORAAmDblOKHzB/model.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='aSPlzcYUamQSWcAAJuzORAAmDblOKHzB/model.proto',
  package='aSPlzcYUamQSWcAAJuzORAAmDblOKHzB',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n,aSPlzcYUamQSWcAAJuzORAAmDblOKHzB/model.proto\x12 aSPlzcYUamQSWcAAJuzORAAmDblOKHzB\"\x17\n\x06\x41\x64\x64Out\x12\r\n\x05value\x18\x01 \x01(\x03\"\x1d\n\x05\x41\x64\x64In\x12\t\n\x01x\x18\x01 \x01(\x03\x12\t\n\x01y\x18\x02 \x01(\x03\x32\x61\n\x05Model\x12X\n\x03\x61\x64\x64\x12\'.aSPlzcYUamQSWcAAJuzORAAmDblOKHzB.AddIn\x1a(.aSPlzcYUamQSWcAAJuzORAAmDblOKHzB.AddOutb\x06proto3')
)




_ADDOUT = _descriptor.Descriptor(
  name='AddOut',
  full_name='aSPlzcYUamQSWcAAJuzORAAmDblOKHzB.AddOut',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='aSPlzcYUamQSWcAAJuzORAAmDblOKHzB.AddOut.value', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=82,
  serialized_end=105,
)


_ADDIN = _descriptor.Descriptor(
  name='AddIn',
  full_name='aSPlzcYUamQSWcAAJuzORAAmDblOKHzB.AddIn',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='aSPlzcYUamQSWcAAJuzORAAmDblOKHzB.AddIn.x', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='y', full_name='aSPlzcYUamQSWcAAJuzORAAmDblOKHzB.AddIn.y', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=107,
  serialized_end=136,
)

DESCRIPTOR.message_types_by_name['AddOut'] = _ADDOUT
DESCRIPTOR.message_types_by_name['AddIn'] = _ADDIN
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AddOut = _reflection.GeneratedProtocolMessageType('AddOut', (_message.Message,), {
  'DESCRIPTOR' : _ADDOUT,
  '__module__' : 'aSPlzcYUamQSWcAAJuzORAAmDblOKHzB.model_pb2'
  # @@protoc_insertion_point(class_scope:aSPlzcYUamQSWcAAJuzORAAmDblOKHzB.AddOut)
  })
_sym_db.RegisterMessage(AddOut)

AddIn = _reflection.GeneratedProtocolMessageType('AddIn', (_message.Message,), {
  'DESCRIPTOR' : _ADDIN,
  '__module__' : 'aSPlzcYUamQSWcAAJuzORAAmDblOKHzB.model_pb2'
  # @@protoc_insertion_point(class_scope:aSPlzcYUamQSWcAAJuzORAAmDblOKHzB.AddIn)
  })
_sym_db.RegisterMessage(AddIn)



_MODEL = _descriptor.ServiceDescriptor(
  name='Model',
  full_name='aSPlzcYUamQSWcAAJuzORAAmDblOKHzB.Model',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=138,
  serialized_end=235,
  methods=[
  _descriptor.MethodDescriptor(
    name='add',
    full_name='aSPlzcYUamQSWcAAJuzORAAmDblOKHzB.Model.add',
    index=0,
    containing_service=None,
    input_type=_ADDIN,
    output_type=_ADDOUT,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_MODEL)

DESCRIPTOR.services_by_name['Model'] = _MODEL

# @@protoc_insertion_point(module_scope)
